### ISSUE TITLE
ED-NeutronRouter wrong forum link (from ED-Router)

### ISSUE THREAD

**Issue by Pulganosaure** [ArNeo-VR/EDVA#9]
Hey, I'm the creator of the ED-Neutron-Router plugin, I wanted to precise, the forum post is not mine, He was posted by the author of ED-Router. His plugin works similar to mine, but require to set up the destination with a visual interface while mine work by selecting a system in the galaxy map. Something i prefer when playing in VR.

I didn't touch my plugin since a long time, if something doesn't work or you have a feature request don't hesitate to send me a message on my project 
Awesome job for your work! It can be useful for a lot of people.

**Comment by ArNeo-VR** [comment]
Hi, Thanks for the comment you are the first 🥇 I really get those plugins names mixed up all the time.

I've made some voice commands for your plugin a while back, last trip was to [Colonia region](https://elite-dangerous.fandom.com/wiki/Colonia_Region).
As I remember, to getting started with the plotting a selecting and plotting a route took a while to figure it out. 
After that It worked fine, sometimes I lost count if the next system was targeted or not. It's also kinda hard with VR to do desktop stuff.
What I'm missing in the plug-in is a reference pointing to your pages.

My intent for this is sharing the commands.
